#!/usr/bin/env python3
import sys
# import itertools

def solve(N: int):
    for i in range(N+1):
        for j in range(N+1):
            for k in range(N+1):
                if i + j + k <= N:
                    print(i, j, k)
    
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
