#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str

def solve(S, T):
    l = ["AC", "AD", "BD", "BE", "CA", "CE", "DB", "DA", "EB", "EC"]
    s = ["AB", "BC", "CD", "DE", "EA", "AE", "ED", "DC", "CB", "BA"]
    if S in l and T in l:
        print(YES)
    elif S in s and T in s:
        print(YES)
    else:
        print(NO)

# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    S = input()
    T = input()
    solve(S, T)

if __name__ == '__main__':
    main()
