#!/usr/bin/env python3
import sys


def solve(N: int, H: "List[int]"):
    ans = -1
    v = H[0]
    for i in range(1,N):
        if v < H[i]:
            ans = i + 1
            break
    print(ans)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    H = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, H)

if __name__ == '__main__':
    main()
