#!/usr/bin/env python3
import sys
import collections

def solve(S: str):
    c = collections.Counter(S)
    a, _ = c.most_common()[-1]
    ans = 0
    for i, s in enumerate(S):
        if s == a:
            ans = i
            break
    print(ans + 1)
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
